app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from .views import index, artists, artist_details

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', index, name='index'),
    path('artists/', artists, name='artists'),
    path('artists/<artist_id>', artist_details, name='artist_details'),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('spotify/', include('spotify.urls')),
]

app/spotify/urls.py
from django.urls import path
from .views import spotify_connect, get_user_data

app_name = 'spotify'

urlpatterns = [
    path('connect/', spotify_connect, name='connect'),
    path('callback/', get_user_data, name='callback'),
]

app/templates/artist_details.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{artist.name}}{% endblock title %}

{% block page_styles %}
<link rel="stylesheet" href="{% static 'css/artist_details.css' %}">
{% endblock page_styles %}

{% block content %}

<h1 class="title" align='center'>{{artist.name}}</h1>

<div class="container">
    <div class="row">
        {% for album in albums %}
            {% include 'partials/album_card.html' %}
        {% endfor %}
    </div>
</div>

{% endblock content %}

app/templates/artists.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Artists{% endblock title %}

{% block page_styles %}
<link rel="stylesheet" href="{% static 'css/artists.css' %}">
{% endblock page_styles %}

{% block content %}

<h1 class="title" align='center'>Artists</h1>

<div class="container">
    <div class="row">
        {% for artist in artists %}
            {% include 'partials/artist_card.html' %}
        {% endfor %}
    </div>
</div>


{% endblock content %}

app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %}</title>
    {% block page_styles %}{% endblock page_styles %}
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Lato" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    {% block content %}
    
    {% endblock content %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock title %}

{% block page_styles %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock page_styles %}

{% block content %}

<a href="{% url 'spotify:connect' %}">Connect to Spotify</a>
<a href="{% url 'logout' %}">Logout</a>
<a href="{% url 'artists' %}">Artists</a>

{% endblock content %}